blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question or discuss an idea
    url: https://discord.gg/S398hSJS
    about: Ask your questions and discuss your ideas in the `#validators-general` channel
